language: go

go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip

matrix:
    fast_finish: true
    allow_failures:
        - go: tip

install: (cd netconf; go get -d -v ./... && go build -v ./...)
before_script:
  - cd netconf
  - go vet ./...
