FROM docker.io/library/golang:1.20-alpine

# required for wait-for-hello.sh script
RUN apk add \
    make \
    build-base \
    openssh \
    sshpass \
    perl-xml-xpath

COPY . /src

WORKDIR /src/inttest
# prebuild
RUN go test -tags=inttest -c .

CMD go test -tags=inttest -v -race .